### ISSUE TITLE
Strange results for the elements of list

### ISSUE THREAD

**Issue by neomen** [google/web-starter-kit#176]
In _list.scss you use icon-bullet type, it's gives strange results

``` css
ul li {
  position: relative;
  padding-left: 16px;
  @include bullet-type("", icon-bullet);

  &::before {
    font-size: 4px;
  }
}
```

![2014-06-24 23-22-30](https://cloud.githubusercontent.com/assets/485453/3374252/13322430-fbbc-11e3-9130-ddf6c06a3f74.png)
