### ISSUE TITLE
Mobile navigation flashes on browser resize

### ISSUE THREAD

**Issue by KevinBatdorf** [google/web-starter-kit#286]
When the user resizes their browser and the mobile navigation kicks in, The mobile nav starts off expanded before sliding off to the side:

![before](https://cloud.githubusercontent.com/assets/1478421/3583562/7572d7ca-0c0b-11e4-8edd-6b53a54aa23c.gif)

There might be a better way, but adding a class of 'opened' to indicate that the use has  viewed the nav at least once could solve this problem with minimal code.

``` javascript
// main.js line 36
function toggleMenu() {
    body.classList.toggle('open');
    appbarElement.classList.toggle('open');
    navdrawerContainer.classList.toggle('open');
    navdrawerContainer.classList.add('opened'); // new
}
```

``` css
/* main.css line 163 */
.app-bar, .navdrawer-container.opened, main { /* added '.opened' */
  -webkit-transition: -webkit-transform 0.3s ease-out;
          transition: transform 0.3s ease-out;
}
```

![after](https://cloud.githubusercontent.com/assets/1478421/3583708/72ba3c24-0c0d-11e4-90dd-b482d0fc9660.gif)
