### ISSUE TITLE
main.scss @font-face url error

### ISSUE THREAD

**Issue by kwcjr** [google/web-starter-kit#744]
I had trouble loading /dist onto my production server. I noticed that the URL structures on all of the @font-face rules may be off by one directory level?

`/app/fonts`
`/app/styles/main.scss`

_gulped_
`/app/fonts`
`/app/styles/main.css`
### Original Source

``` scss
@font-face {
  font-family: 'Roboto Condensed';
  font-style: normal;
  font-weight: 300;
  src: url(/fonts/RobotoCondensed-Light.eot);
  src: local('Roboto Condensed Light'), local('RobotoCondensed-Light'), url(/fonts/RobotoCondensed-Light.eot) format('embedded-opentype'), url(/fonts/RobotoCondensed-Light.woff) format('woff');
}
```
### Replace with

``` scss
@font-face {
  font-family: 'Roboto Condensed';
  font-style: normal;
  font-weight: 300;
  src: url(../fonts/RobotoCondensed-Light.eot);
  src: local('Roboto Condensed Light'), local('RobotoCondensed-Light'), url(../fonts/RobotoCondensed-Light.eot) format('embedded-opentype'), url(../fonts/RobotoCondensed-Light.woff) format('woff');
}
```
